pickup/urls.py
from django.conf.urls import patterns, include, url
#from django.conf.urls import *
import notifications
import actstream

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pickup.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'pickupApp.views.index', name='index'),
    url(r'^about/', 'pickupApp.views.about', name='about'),
    url(r'^register/', 'pickupApp.views.register', name='register'),
    url(r'^home/', 'pickupApp.views.home', name='home'),
    url(r'^login/', 'pickupApp.views.user_login', name='user_login'),
    url(r'^create_game/', 'pickupApp.views.create_game', name='create_game'), 
    url(r'^logout/', 'pickupApp.views.logout_view', name='logout'),
    url(r'^user_login/', 'pickupApp.views.user_login', name='user_login'),    
    url(r'^team/', 'pickupApp.views.team', name='team'), 
    url(r'^get_games/', 'pickupApp.views.get_games', name='get_games'),
    url(r'^game/(\d+)$', 'pickupApp.views.game'), 
    url(r'^join_quit_game/', 'pickupApp.views.join_quit_game', name='join_quit_game'),
    url(r'^delete_game/', 'pickupApp.views.delete_game', name='delete_game'),
    url(r'^sport/(\w+)$', 'pickupApp.views.sport', name='sport'),
    url(r'^user/(\d+)$', 'pickupApp.views.user', name='user'), 
    url(r'^inbox/notifications/', include(notifications.urls)),
    url(r'^activity/', include('actstream.urls')),
    url(r'^remove_notifications/', 'pickupApp.views.remove_notifications', name='remove_notifications'),
    url(r'^profile/', 'pickupApp.views.profile', name='profile'),
    url(r'^sports/', 'pickupApp.views.sports', name='sports'),   
    url(r'^search/', 'pickupApp.views.search', name='search'), 
    # url(r'', include('social_auth.urls')),
    url(r'^comment/', 'pickupApp.views.comment', name='comment'), 
    url(r'^instagram_login/', 'pickupApp.views.instagram_login', name='instagram_login'),
    url(r'^get_instagram_photos/(\d+)$', 'pickupApp.views.get_instagram_photos', name='get_instagram_photos'),
    url(r'^post_photos/', 'pickupApp.views.post_photos', name='post_photos'),
    url(r'^upload_profile_photo/', 'pickupApp.views.upload_profile_photo', name='upload_profile_photo'),
    url(r'^toggle_follow/','pickupApp.views.toggle_follow',name='toggle_follow'),
    url(r'^analytics/', 'pickupApp.views.analytics', name='analytics'),
    url(r'^first_login/', 'pickupApp.views.first_login', name='first_login'),
    url(r'^first_login2/', 'pickupApp.views.first_login2', name='first_login2'),
    url(r'^invite_friends/(\d+)$', 'pickupApp.views.invite_friends', name='invite_friends'),
    url(r'^recommendations/', 'pickupApp.views.recommendations', name='recommendations'),   
    url(r'^store_user_location/', 'pickupApp.views.store_user_location', name='store_user_location'),   
)

# urlpatterns = urlpatterns + 
#     patterns('',
#         url(r'^inbox/notifications/', include(notifications.urls)),
#     )

pickupApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Location(models.Model):
	name = models.CharField(max_length=300)
	latitude = models.FloatField()
	longitude = models.FloatField()
	
class Sport(models.Model):
	name = models.CharField(max_length=200)
	lovers = models.ManyToManyField(User, through='UserSportLevel')

class Game(models.Model):
	#sport = models.CharField(max_length=50, null=True)
	name = models.CharField(max_length=50)
	description = models.CharField(max_length=400)
	#location = models.CharField(max_length=300, null=True)
	dateCreated = models.DateTimeField(null=True)
	timeStart = models.DateTimeField(null=True)
	cap = models.IntegerField()
	# Need an owner (user) of the game
	creator = models.ForeignKey(User, related_name = "creator_of_game")
	location = models.ForeignKey(Location)
	users = models.ManyToManyField(User) # Game will have users that have signed up for the game
	sport = models.ForeignKey(Sport)

	@property
	def sorted_comment_set(self):
	    return self.comment_set.order_by('-timeStamp')

class Comment(models.Model):
	text = models.TextField()
	timeStamp = models.DateTimeField(null=True)
	game = models.ForeignKey(Game)
	commenter = models.ForeignKey(User)


class InstagramInfo(models.Model):
	# {u'access_token': u'1105726448.9135221.702125d2abb24aa49e410d1ac9c6fabc', 
	# u'user': 
	# {u'username': u'eymyers', u'bio': u'', u'website': u'', u'profile_picture': u'http://images.ak.instagram.com/profiles/anonymousUser.jpg', u'full_name': u'Ethan Myers', u'id': u'1105726448'}}

	access_token = models.CharField(max_length=200)
	username = models.CharField(max_length=200)
	profile_picture = models.CharField(max_length=200)
	full_name = models.CharField(max_length=200)
	instagramID = models.IntegerField()
	user = models.OneToOneField(User,null=False)

class GamePhoto(models.Model):
	thumbnail = models.URLField()
	standard = models.URLField()
	game = models.ForeignKey(Game)

class UserInfo(models.Model):
	profile_picture = models.URLField(default='http://fashionlawsymposium.com/wp-content/uploads/2013/10/person-placeholder.jpg')
	latitude = models.FloatField(null=True)
	longitude = models.FloatField(null=True)
	user = models.OneToOneField(User)

class UserSportLevel(models.Model):
	user = models.ForeignKey(User)
	sport = models.ForeignKey(Sport)
	level = models.IntegerField(default=0)
	

pickupApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from pickupApp.forms import RegisterForm, LoginForm, GameForm, CommentForm
from pickupApp.models import Game, Location, Comment, InstagramInfo, GamePhoto, UserInfo, Sport, UserSportLevel
import datetime
import json, ast
from django.http import HttpResponse
from pickupApp.constants import location_to_coordinates
from collections import defaultdict
from pickupApp.constants import sports_dict
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.messages import get_messages
from notifications import notify
from django.db.models import Q
from pickup.settings import INSTAGRAM_ID, INSTAGRAM_SECRET, REDIRECT_URL, FACEBOOK_APP_ID, FACEBOOK_URL
import urllib2, urllib
from instagram.client import InstagramAPI

# For Django Activity Stream
from django.db.models.signals import post_save
from actstream import action 
from actstream.models import Action, user_stream, actor_stream, action_object_stream, model_stream, following, followers
from actstream.actions import follow,unfollow

from django.core import serializers
import math, operator



# -------------------------------------------------------------------- #
# Renders the landing page
# -------------------------------------------------------------------- #
def index(request):
	print request.user
	if request.user.is_authenticated():
		return redirect('/home')

	num_games = get_num_games()
	messages = get_messages(request)
	return render(request, 'index.html', {'num_games':num_games, 'messages':messages})

def get_num_games():
	num_games = defaultdict(lambda:0)
	all_games = Game.objects.all()
	for game in all_games: 
		num_games[game.sport.name] += 1

	return num_games

# -------------------------------------------------------------------- #
# Gets all game data and puts it in a specific format we use later (json)
# -------------------------------------------------------------------- #
@login_required
def get_games(request):
	upcoming_games = Game.objects.filter(timeStart__gte=datetime.datetime.now()).order_by('timeStart');
	games_data = {}
	for game in upcoming_games:
		location = game.location.name
		
		if not location in games_data:
			info = {}
			games_info = []
			location_info = {}
			location_info['latitude'] = game.location.latitude
			location_info['longitude'] = game.location.longitude
			info['location_info'] = location_info
			info['games'] = games_info
			
			games_data[location] = info

		game_data = {}
		game_data['id'] = game.id
		game_data['name'] = game.name
		game_data['creator'] = game.creator.first_name+' '+game.creator.last_name
		game_data['description'] = game.description
		#game_data['time_start'] = game.timeStart
		game_data['sport'] = game.sport.name
		game_data['curr_num_players'] = game.users.count()
		game_data['max_num_players'] = game.cap
		#game_data['location'] = game.location

		games_data[location]['games'].append(game_data)
	return games_data
	#return HttpResponse(json.dumps(games_data), content_type="application/json")


# -------------------------------------------------------------------- #
# Function is called when home page is rendered
# Gives the home page the necessary data to render
# -------------------------------------------------------------------- #
@login_required
def home(request):
	games_data = get_games(request)
	mystream = user_stream(request.user)
	all_actions = mystream.filter(timestamp__lt=datetime.datetime.now()).order_by('-timestamp');
	following_people = following(request.user)
	if not len(following_people):
		all_actions = []
	messages = get_messages(request)
	
	# unread = request.user.notifications.unread()
	# for note in unread:
	# 	print note.verb

	game_recommendations = []
	if request.user.userinfo.latitude != None:
		game_recommendations = get_game_recommendations(request)

	return render(request, 'home.html', {
		'user'					:request.user, 
		'games_json'			:json.dumps(games_data), 
		'messages'				:messages,
		'actions' 				:all_actions,
		'game_recommendations' 	:game_recommendations
		})


# -------------------------------------------------------------------- #
# Registering a new user
# -------------------------------------------------------------------- #
def register(request):
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid():
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			email = form.cleaned_data['email']	
			password = form.cleaned_data['password']
			
			if not User.objects.filter(username=email).count():
				# need an if here to check if passwords match
				new_user = User.objects.create_user(email, email, password)
				new_user.first_name = first_name
				new_user.last_name = last_name
				new_user.save()

				userinfo = UserInfo.objects.create(user=new_user)

				user = authenticate(username=email, password=password)
				login(request, user)
				verb = first_name + ' ' + last_name + " created an account!"

				#action.send(user,verb=verb)
				return redirect('/first_login')
				
			else:
				print form.errors
				return redirect('/')
		else:
			print "INVALID FORM"
			print form.errors
			return redirect('/')
	else:
		print "GET"
		first_name = form.cleaned_data['first_name']
		last_name = form.cleaned_data['last_name']
		form = RegisterForm()
		return redirect('/')


# -------------------------------------------------------------------- #
# Creating a new game
# -------------------------------------------------------------------- #
@login_required
def create_game(request):
	if request.method == 'POST':
		form = GameForm(request.POST)
		if form.is_valid():
			sport = form.cleaned_data['sport']
			name = form.cleaned_data['name']
			cap = form.cleaned_data['cap']
			description = form.cleaned_data['description']
			location_name = form.cleaned_data['location']
			location = Location.objects.get(name=location_name)

			#Need to handle time zones
			datetimeStart = request.POST['dtp_input1']

			sportObj = Sport.objects.get(name=sport.lower())
			newGame = Game.objects.create(sport=sportObj,name=name,timeStart=datetimeStart, creator=request.user, location=location, cap=cap, description=description)
			newGame.dateCreated = datetime.datetime.now()
			newGame.users.add(request.user)
	
			newGame.save()
			action.send(request.user,verb="game created",action_object=newGame)
			return redirect('/game/'+str(newGame.id))
		else:
			print 'invalid form'
			error_msg = 'Could not create your game. Please try again!'
			return render(request, 'create_game.html', {'gameForm':form, 'error_msg':error_msg})
	else:
		gameForm = GameForm()
		return render(request, 'create_game.html', {'gameForm':gameForm})


# -------------------------------------------------------------------- #
# Logs the user in or redirects of bad login
# -------------------------------------------------------------------- #
def user_login(request):
	if request.method == 'POST': 
		form = LoginForm(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']	
			password = form.cleaned_data['password']

			user = authenticate(username=email, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('/home')
				else:
					return render(request, 'in.html', {'loginForm':form})
			else:
				msg = 'Invalid username and password.'
				messages.error(request, msg)
				return redirect('/')
		else:
			msg = 'Invalid username and password.'
			messages.error(request, msg)
			return redirect('/')
	else:
		return redirect('/')


# -------------------------------------------------------------------- #
# Function is called whenever a game page is rendered
# Function gets all the necessary data to populate the game page
# -------------------------------------------------------------------- #
@login_required
def game(request,id):
	game_exists = Game.objects.filter(id=id).count()
	if game_exists:
		game = Game.objects.get(id=id)
		print action_object_stream(game)

		comment_form = CommentForm(initial={'user_id': request.user.id, 'game_id':game.id})
	
		# Check whether the game has already happened
		if game.timeStart.replace(tzinfo=None) < datetime.datetime.now():
			passed_game = True
		else:
			passed_game = False

		# Check if the game player has maxed
		maxed = False
		if game.cap:
			if game.users.count() >= game.cap:
				maxed = True


		# Check if user is the creator of the game
		is_creator = False
		if request.user == game.creator:
			is_creator = True

		# Check if user has joined the game
		joined = False
		if request.user in game.users.all() or is_creator:
			joined = True

		connected_to_instagram = False
		if InstagramInfo.objects.filter(user=request.user).count():
			connected_to_instagram = True

		return render(request, 'game.html', {
			'game':game, 
			'joined':joined, 
			'is_creator':is_creator, 
			'user':request.user, 
			'game_exists':game_exists, 
			'passed_game':passed_game, 
			'maxed':maxed, 
			'comment_form':comment_form, 
			'connected_to_instagram':connected_to_instagram,
			'instagramID' : INSTAGRAM_ID,
			'instagramSecret' : INSTAGRAM_SECRET,
			'redirectURL' : REDIRECT_URL,
		})
	else:
		return render(request, 'game.html', {'game_exists':game_exists})
	
# -------------------------------------------------------------------- #
# Function is called when a user wants to quit or join a game
# -------------------------------------------------------------------- #
@login_required
def join_quit_game(request):
	#userID = request.user.id
	response = ''
	if request.method == 'POST': 
		game_id = request.POST['game_id']
		print game_id
		
		game = Game.objects.get(id=game_id)
		if request.user in game.users.all():
			game.users.remove(request.user)
			response = 'left'

pickupApp/templates/analytics.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<section>
		<h3>Analytics</h3>
		<div id="player"  class="col-md-4" style="width:35%" >
			<h5>Your Analytics</h5>
			<p><b>You have played {{games_played.count}} games</b></p>
		</div>
		<div id="game"  class="col-md-4" style="width:35%">
			<h5>Game Analytics</h5>
			<p><b>{{all_games_played.count}} games played overall</b></p>
	  </div>
	  <div id="sport" class="col-md-4" style="width:30%">
			<h5>Sport Analytics</h5>
			<p> <b> Top locations by sport: </b> <p>
	   </div> 


	    <div id="piechart_3d"  class="col-md-4" style="width: 35%; height: 300px;" align="left"></div>
			
		 <script type="text/javascript" src="https://www.google.com/jsapi"></script>
	     <script type="text/javascript">
	     	 google.load("visualization", "1", {packages:["corechart"]});
	     	 google.setOnLoadCallback(drawChart);
	     	 var mySportsArr=new Array();
	     	 mySportsArr.push(['Sport', 'Games Played'])
	     	 {% for sport in fav_sports %}
				   mySportsArr.push(["{{sport.0}}", {{sport.1}}])
			{% endfor %}
			function drawChart() {
				var data = google.visualization.arrayToDataTable(mySportsArr);

				var options = {
				  title: 'My Sports Breakdown',
				  is3D: true,
				};
				var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
				var options = {
					colors: ['#e0440e', '#e6693e', '#ec8f6e', '#f3b49f', '#f6c7b6']
				};
				chart.draw(data, options);
				}		
	     </script>

			<div id="piechart_3d_2" class="col-md-4" style=" width: 35%; height: 300px;" align="left"></div>
			
			 <script type="text/javascript" src="https://www.google.com/jsapi"></script>
	    <script type="text/javascript">

	     	 google.load("visualization", "1", {packages:["corechart"]});
	     	 google.setOnLoadCallback(drawChart_2);
	     	 var mySportsArr2=new Array();
	     	 mySportsArr2.push(['Sport', 'Games Played'])
	     	 {% for sport,num in games_played_breakdown.iteritems %}
				   mySportsArr2.push(["{{sport}}", {{num}}])
			{% endfor %}
			function drawChart_2() {
			    var data = google.visualization.arrayToDataTable(mySportsArr2);

			    var options = {
			      title: 'Sports Breakdown',
			      is3D: true,
			    };
			    var chart = new google.visualization.PieChart(document.getElementById('piechart_3d_2'));
			    var options = {
					colors: ['FF00CC',	'FF33FF',	'FF66FF',	'FF99FF',	'FFCCFF']
				};
			    chart.draw(data, options);
			}
	     </script>

	    <div class="col-md-4" style="margin-top:50px ; width: 30%" align="left">
	    	{% for k,v in sorted_freq_places.iteritems %}
			<div><img src="/static/images/{{k}}.png"></img>  <b>{{k}}: </b> {{v.0.1}} games at {{v.0.0}}</div>
			{% endfor %}
		</div> 


	</section>
</div>

{% endblock %}

pickupApp/templates/first_login.html
{% extends "base.html" %}

{% block navlist %}
{% endblock %}

{% block content %}
<div class="container">
	<section>
		<h3>Welcome to Reqtime, {{user.first_name}}!</h3>
		<div class="progress">
		  <div class="progress-bar" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%;">
		    30%
		  </div>
		</div>
		<div>
			<h5>What are you favorite sports?</h5>
			<br/>
			<div id="sports_select">
				<ul>
					<li><a href="#" value="basketball">Basketball</a></li>
					<li><a href="#" value="football">Football</a></li>
					<li><a href="#" value="frisbee">Frisbee</a></li>
					<li><a href="#" value="golf">Golf</a></li>
					<li><a href="#" value="soccer">Soccer</a></li>
					<li><a href="#" value="volleyball">Volleyball</a></li>
				</ul>
			</div>
		</div>
		<br />
		<div>
			<a type="button" id="next_step_button" class="btn btn-primary disabled" style="float:right">Next</a>
		</div>
	</section>
</div>
{% endblock %}

{% block javascript %}
<script>
$("#next_step_button").click(function() {
	$.ajax({
	  type: "POST",
	  url: "/first_login/",
	  data: { 
	    'csrfmiddlewaretoken':'{{csrf_token}}',
	    'sports': localStorage.getItem("sports")
	  },
	  success: function(data) {
	  	localStorage.clear();
	    window.location.href = '/first_login2';
	  },
	});
});
</script>
<script src="/static/js/first_login.js"></script>
{% endblock %}

pickupApp/templates/game.html
{% extends "base.html" %}
{% block title %}{{game.name}}{%endblock%}
{% block content %}

 <!-- SignUp Modal -->
    <div class="modal fade" id="photosModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> </div>
    <div class="modal fade" id="friendsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> </div> 
<!-- <section class= "overlay" style="background-image: url(/static/images/{{game.sport}}.jpg); overflow:scroll" >
 --><section class= "overlay" style="background-image: url(/static/img/white_wall.png); overflow: scroll;" >
  <div class="container" >
    {% if game_exists %}
    <h2 style="">{{game.name}}
      {% if is_creator %}
      (creator)
      {% endif %}
    </h2>
    <div> 
    {% if not passed_game %}
      {% if is_creator %}
        <form role="form" action="/delete_game/" method="POST" id="delete_form">{% csrf_token %}
          <input type="hidden" name="game_id" value="{{game.id}}">
        </form>
        <button type="button" class="btn btn-danger delete_button" id="delete">
          <i class="fa fa-trash-o fa-lg"></i> Delete Game
        </button> 
        
        <a type="button" class="btn btn-asphalt" href='/invite_friends/{{game.id}}' id="" data-toggle="modal" data-target="#friendsModal"> Invite Players </a>

        {% if connected_to_instagram %}
        <a type="button" class="btn btn-instagram instagram" href='/get_instagram_photos/{{game.id}}' id="" data-toggle="modal" data-target="#photosModal">
          <i class="fa fa-camera-retro"></i> | Post Photos From Instagram
        </a>
        {% else %}
        <a type="button" class="btn btn-instagram instagram" href='https://api.instagram.com/oauth/authorize/?client_id={{instagramID}}&redirect_uri={{redirectURL}}&response_type=code'>
            <i class="fa fa-camera-retro"></i> | Connect to Instagram to Post Photos
        </a>
        {% endif %} 
      {% else %}
        {% if not maxed %} 
          <form role="form" action="/join_quit_game/" method="POST" id="join_form">{% csrf_token %}
            <input type="hidden" name="game_id" value="{{game.id}}">
          </form>
          {% if not joined %}
            <button type="button" class="btn btn-success join_button" id="join">
              <i class="fa fa-plus fa-med"></i> Join</button>    
          {% else %}
            <button type="button" class="btn btn-danger join_button" id="leave">
              <i class="fa fa-minus fa-lg"></i> Leave</button>
            <a type="button" class="btn btn-asphalt" href='/invite_friends/{{game.id}}' id="" data-toggle="modal" data-target="#friendsModal"> Invite Players </a> 
            {% if connected_to_instagram %}
            <a type="button" class="btn btn-instagram instagram" href='/get_instagram_photos/{{game.id}}' id="" data-toggle="modal" data-target="#photosModal">
          <i class="fa fa-camera-retro"></i> | Post Photos From Instagram </a>
            {% else %}
            <a type="button" class="btn btn-instagram instagram" href='https://api.instagram.com/oauth/authorize/?client_id={{instagramID}}&redirect_uri={{redirectURL}}&response_type=code'>
                <i class="fa fa-camera-retro"></i> | Connect to Instagram to Post Photos
            </a>
            {% endif %}
          {% endif %}
        {% else %}
          <p>Sorry! All game spots are filled.</p>
        {% endif %}
      {% endif %}
    {% else %}
      {% if connected_to_instagram %}
        <a type="button" class="btn btn-instagram instagram" href='/get_instagram_photos/{{game.id}}' id="" data-toggle="modal" data-target="#photosModal">
          <i class="fa fa-camera-retro"></i> | Post Photos From Instagram
        </a>
      {% endif %}

    {% endif %}
  </div> 
 
  <div style="display:block">
    <div class="transbox left" >
      <p  class="players">Name: {{game.name}}</p>
      <p  class="players">Creator: <a href="/user/{{game.creator.id}}">{{game.creator.first_name}} {{game.creator.last_name}}</a></p>
      <p  class="players">Sport: <a href="/sport/{{game.sport.name}}">{{game.sport.name}}</a></p>
      <p  class="players">Location: {{game.location.name}}</p>
      <p  class="players">Time: {{game.timeStart}}</p>
      <p  class="players">Description: {{game.description}}</p>
      <p  class="players">Players
        <ol>
          {% for player in game.users.all %}
          <li id="{{player.id}}" class="players"><a href="/user/{{player.id}}"><img src="{{player.userinfo.profile_picture}}" class="avatar" />{{player.first_name}} {{player.last_name}}</a></li>
          {% endfor %}
        </ol>
      </p>
    </div> 
    <div id='map-canvas' style="width:45%; margin-left:2px"></div>
    {% else %}
    <h2>This game does not exists.</h2>
    {% endif %}
  </div>
  <div style="display:block; margin-top:400px">

    {% if game.gamephoto_set.all.count %}
    <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
    <div id="blueimp-gallery" class="blueimp-gallery">
        <!-- The container for the modal slides -->
        <div class="slides"></div>
        <!-- Controls for the borderless lightbox -->
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
        <!-- The modal dialog, which will be used to wrap the lightbox content -->
        <div class="modal fade">
            <div class="modal-dialog space-top">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close black" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body next"></div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left prev">
                            <i class="glyphicon glyphicon-chevron-left"></i>
                            Previous
                        </button>
                        <button type="button" class="btn btn-primary next">
                            Next
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="game_photos" style="width:100%">
      <h3>Game Photos</h3>
       <div id="links">
      {% for game_photo in game.gamephoto_set.all %}
       <a href="{{game_photo.standard}}"  data-gallery>
        <img src="{{game_photo.thumbnail}}" style="width:200px; height:200px">
    </a>
      {% endfor %}
      </div>
    </div>
    {% endif %}

   <h3> Discussion thread </h3> 
    <div class="comment_box" style="margin-top:10px; margin-right:10px; width:45%; float:left">
      <form class="form-horizontal" role="form" action="/comment/" method="POST">{% csrf_token %}
        {{comment_form.text}}
        {{comment_form.user_id}}
        {{comment_form.game_id}}
        <button type="submit" class="btn btn-primary" style ="margin-top:15px">Post</button>
      </form>
    </div> 
  </div>
       {% if game.comment_set.all.count %}
      <ul class="media-list">
        {% for comment in game.sorted_comment_set %}
        <li class="media">
          <a class="pull-left" href="#">
            <img class="media-object" data-src="">
          </a>
        </li>
        <div class="media-body" style="float:right; width:50%">
              <h4 class="media-heading">{{comment.commenter.first_name}} {{comment.commenter.last_name}}</h4>
            {{comment.text}}
            {{comment.timeStamp}}
        </div>
        {% endfor %}
      </ul>
      {% endif %}
    </div> 
    </div>
  </div>
 

<style type="text/css">
 #map-canvas {
    width: 500px;
    height: 400px;
    float:right;
  }
</style> 

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<!-- Cannot pull this out as the google map won't show up -->
<script>  
  function initialize() {
    var myLatlng = new google.maps.LatLng({{game.location.latitude}}, {{game.location.longitude}});
    var mapOptions = {
    zoom: 15,
    center: myLatlng,
    }
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    var image = {
    url: "/static/images/{{game.sport}}.png",
    size: new google.maps.Size(71, 71),
    origin: new google.maps.Point(0, 0),
    anchor: new google.maps.Point(17, 34),
    scaledSize: new google.maps.Size(25, 25)
    };
    var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      //icon:image,
    });

  }google.maps.event.addDomListener(window, 'load', initialize);
</script>
<script src="/static/js/game.js"></script> 

</section>
{%endblock%}



{% block javascript %}

<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> -->
<script src="/static/js/jquery.blueimp-gallery.min.js"></script>
<script src="/static/js/bootstrap-image-gallery.min.js"></script>

<!-- <script type="text/javascript"></script> -->
{% endblock %}

pickupApp/templates/game_update_form.html
{% extends "base.html" %}
{% block content %}
<div class="container">
	<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
</div>
{% endblock %}

pickupApp/templates/recommendations.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<section>
		<h3>Recommendations</h3>
	</section>
</div>
{% endblock %}